import { ethers } from "hardhat";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function main() {
  console.log("Deploying HealthcareConsent to local Hardhat node...\n");

  const [deployer] = await ethers.getSigners();
  console.log(`Deployer address : ${deployer.address}`);
  console.log(`Deployer balance : ${ethers.formatEther(await deployer.provider.getBalance(deployer.address))} ETH\n`);

  const HealthcareConsent = await ethers.getContractFactory("HealthcareConsent");
  const contract = await HealthcareConsent.deploy();
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log(`✅  HealthcareConsent deployed to: ${address}`);
  console.log(`    Block: ${(await contract.deploymentTransaction().wait()).blockNumber}`);

  // ─── Write deployment info ──────────────────────────────────────────────
  const deploymentInfo = {
    contractName: "HealthcareConsent",
    address,
    network: "localhost",
    chainId: 31337,
    deployer: deployer.address,
    deployedAt: new Date().toISOString(),
    abi: JSON.parse(
      fs.readFileSync(
        path.join(__dirname, "../artifacts/contracts/HealthcareConsent.sol/HealthcareConsent.json"),
        "utf8"
      )
    ).abi,
  };

  const outPath = path.join(__dirname, "../deployment.json");
  fs.writeFileSync(outPath, JSON.stringify(deploymentInfo, null, 2));
  console.log(`\n📄 Deployment info saved → ${outPath}`);

  // ─── Also write ABI to frontend for easy import ─────────────────────────
  const frontendDir = path.join(__dirname, "../../frontend/src");
  if (fs.existsSync(frontendDir)) {
    const frontendPath = path.join(frontendDir, "contractConfig.js");
    fs.writeFileSync(
      frontendPath,
      `// Auto-generated by deploy.js\nexport const CONTRACT_ADDRESS = "${address}";\nexport const CONTRACT_ABI = ${JSON.stringify(deploymentInfo.abi, null, 2)};\n`
    );
    console.log(`📄 Contract config written → ${frontendPath}`);
  }

  // ─── Demo: grant a consent on-chain ────────────────────────────────────
  const signers = await ethers.getSigners();
  const patient = signers[1];
  const provider = signers[2];

  console.log("\n🔗 Demo: granting consent on-chain...");
  const tx = await contract.connect(patient).grantConsent(
    provider.address,
    86400, // 24 hours
    "Cardiology"
  );
  const receipt = await tx.wait();
  console.log(`   ConsentGranted tx: ${receipt.hash}`);

  console.log("\n🎉 Deployment complete!");
}

try {
  await main();
  process.exit(0);
} catch (err) {
  console.error("Deployment failed:", err);
  process.exit(1);
}
